name = "m10c"
license = "MIT"
licenselink = "https://github.com/pgg21/hugo-theme-m10c/blob/master/LICENSE.md"
description = "A minimalistic (m10c) theme for bloggers"
homepage = "https://github.com/pgg21/hugo-theme-m10c"
tags = ["blog", "minimalistic", "minimal", "responsive", "dark"]
features = [
  "minimalistic blog",
  "social icons",
  "editable colors"
]

[author]
  name = "pgg21"
  homepage = "https://github.com/pgg21"
